#!/bin/sh
PATH_TO_APP=/usr/bin/aesdsocket

start-stop-daemon --status --name aesdsocket
retval=$?
if [ $retval -ne 0 ]; then
    start-stop-daemon --name aesdsocket --start --startas $PATH_TO_APP -- -d
    retval=$?
    if [ $retval -ne 0 ]; then
        echo "$0: [ERROR] start-stop-daemon returned $retval on start"
    else
        echo "$0: aesdsocket started"
    fi
else
    start-stop-daemon --stop --signal TERM --name aesdsocket
    retval=$?
    if [ $retval -ne 0 ]; then
        echo "$0: [ERROR] start-stop-daemon returned $retval on kill"
    else
        echo "$0: aesdsocket killed"
    fi
fi
