#!/bin/sh
PATH_TO_APP=/usr/bin/aesdsocket

start-stop-daemon -K -t -x /usr/bin/aesdsocket
retval=$?
if [ $retval -ne 0 ]; then
    start-stop-daemon -S -x /usr/bin/aesdsocket -- -d    
    retval=$?
    if [ $retval -ne 0 ]; then
        echo "$0: [ERROR] start-stop-daemon returned $retval on start"
    else
        echo "$0: aesdsocket started"
    fi
else
    start-stop-daemon -K -s TERM -x /usr/bin/aesdsocket
    retval=$?
    if [ $retval -ne 0 ]; then
        echo "$0: [ERROR] start-stop-daemon returned $retval on kill"
    else
        echo "$0: aesdsocket killed"
    fi
fi
